### ISSUE TITLE
Write down hopr-server resource spec in protonbuf

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-core#117]
# Introduction
As we are moving to setting up a daemon-like process that is able to run hopr-core in the background and understand commands via a gRPC interface, we need to setup the common connector interface in protobuf compatible resources as to be used for hopr-server.

# Task Description
- [x] Read about protobuf and gRPC (recommended readings at the bottom)
- [x] Create a folder called `server` inside `hopr-core`, and a README and a server that loads `.proto` files
- [ ] Create `.proto` files representing the hopr-server resources (architecture at the bottom)
- [x] Create a visualisation of the `.proto` files and include it in the README

# Definition of Complete
The task is considered completed when all Stage 0 to 3 defined resources had been defined as protobuf resources.

# Testing Criteria
- [ ] A gRPC enabled server is started when running `yarn start` inside `hopr-core/server`
- [ ] All resources and operations are documented in the Web Server architecture as `.proto` files

# Notes

### Web Architecture MVP
```
Web Server MVP Architectural

node server.js --usesCoverTraffic=true --logLevel=4 ...

hopr-server
  |_ @hoprnet/hopr-core

server.ts
\__ import { default as HOPR } from '@hoprnet/hopr-core'
      const hoprNode = new HOPR({...})
      hoprNode.send(...)


Stage 0 - describe               GET   /status ({} => { ip, load, cpu_usage, connected_nodes })
Stage 0 - describe               GET   /version ({} => { version, components_version })
Stage 0 - quit                      POST /shutdown ({} => { timestamp })
Stage 0 - ping                     POST /ping ({peerId} => { pingReceipt:latency })
Stage 0 - .env                      POST /settings ({Settings:bootstrap_servers, is_using_cover_traffic})

Stage 1 - balance               GET   /balance/native ({} => { amount })
Stage 1 - balance               GET   /balance/hopr ({} => { amount })
Stage 1 - myAddress         GET   /address/native ({} => { amount })
Stage 1 - myAddress         GET   /address/hopr ({} => { amount })

Stage 2.a - listChannel      GET   /channels ({} => { open_channel[] })
Stage 2.a - openChannel  POST  /channels ({peerId} => channelTxReceipt:{channelId,...})
Stage 2.a - listChannel     GET    /channels/:channelId ({channelId} => { state, balance, ... })
Stage 2.a - closeChannel  POST  /channels/:channelId/close ({channelId} => channelTxReceipt)
Stage 2.b - crawl               POST  /crawl ({} => connected_nodes[])
Stage 2.b - listen*              POST /listen ({} => EventHandler) // e.g. on.message(..., fn)
Stage 2.b - send                 POST /send ({peerID, payload, [intermediatePeerIds[], timeout]} => txReceipt)

Stage 3 - transfer*            POST /transfer/native ({address, amount} => txReceipt)
Stage 3 - transfer*            POST /transfer/hopr ({address,amount} => txReceipt)
```

### Recommended readings about gRPC
- https://www.youtube.com/watch?v=RtyKEDZipsM&t=734s
- https://cloud.google.com/blog/products/api-management/understanding-grpc-openapi-and-rest-and-when-to-use-them
- https://devopedia.org/grpc
- https://codelabs.developers.google.com/codelabs/cloud-grpc/index.html

**Comment by nionis** [comment]
Implemented Stage 0 to Stage 2.a

**Comment by 0xjjpa** [comment]
@nionis Let's create a `README` with this spec and close this issue.

**Comment by 0xjjpa** [comment]
To be continued in https://github.com/hoprnet/hopr-core/issues/179, the proto initial work has already being laid down here. Closing.
