### ISSUE TITLE
Feedback from HOPR Testnet Launch

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-core#197]
# Description
* Users sometimes would not be able to find peers:
```
Error: No peer found
    at Object.findPeer (/home/seb/Downloads/hopr-chat/index.js:78628:23)
    at async /home/seb/Downloads/hopr-chat/index.js:19602:24
    at async /home/seb/Downloads/hopr-chat/index.js:188860:19
```
* Users would receive an odd encoding message sometimes:
```
> 
===== New message ======
Message: 
          ��>�/G�$r�����
Latency: 1678 ms
========================
```
* Default colour (blue) for the `Destination` field looks quite bad with Powershell.
![image.png](https://images.zenhubusercontent.com/5bec49ea4b5806bc2bf49d54/41f6a197-4d98-4f63-ab92-2fbfee2a6c26)

# Tasks
- [ ] Execute some tests for HOPR nodes behind different networks/regions and/or VPNs.
- [ ] Ensure text encoding is done against utf-8, as to avoid sending parsing hex content.
- [ ] Change `Destination` field color scheme when sending messages. Test on Powershell.
